api:
  dashboard: true
  # insecure: true # Don't do that in production

# Entrypoints
entryPoints:
  web:
    address: :8001

  websecure:
    address: :4430
    
# Providers
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

log:
  filePath: "/traefik/logs/traefik.log"
  format: json

accessLog:
  filePath: "/traefik/logs/access.log"