name: Renovate
on:
  schedule:
    - cron: '0 3 * * 0' # Run at 3 AM every Sunday
  workflow_dispatch: # Allow manual triggering
  push: # todo delete before merge
    branches:
      - renovate

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v43.0.6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          configurationFile: renovate.json5