name: Unit test suite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
# commented permission only needed for private repository
#  contents: read
#  issues: read
  checks: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6
        with:
          python-version: '3.13'
      - name: Setup .env
        run: |
          touch .env && make init-env
      - name: Start Development Environment
        id: dev-environment
        run: make run-dev-build -e DOCKER_COMPOSE_OPTIONS="-d"
        continue-on-error: true

      - name: Capture Container Logs
        if: steps.dev-environment.outcome == 'failure'
        run: |
          mkdir -p logs
          docker compose --profile dev logs > logs/docker-compose.log
          echo "::error::Development environment failed to start - check uploaded logs"

      - name: Upload Container Logs
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        if: steps.dev-environment.outcome == 'failure'
        with:
          name: container-logs
          path: logs/docker-compose.log
          retention-days: 5
          if-no-files-found: error

      - name: Fail if Dev Environment Failed
        if: steps.dev-environment.outcome == 'failure'
        run: exit 1

      - name: Initialize Database
        run: make init-db

      - name: Run Tests
        run: make pytest

      # human-readable report
      - name: Upload HTML Coverage Report
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: coverage-html-report
          path: reports/coverage
          retention-days: 14

      # useful for tools like SonarQube
      - name: Upload XML Coverage Report
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: coverage-xml-report
          path: reports/coverage.xml
          retention-days: 14

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@3a74b2957438d0b6e2e61d67b05318aa25c9e6c6 # v2
        if: always()
        with:
          test_file_prefix: "+backend/app"
          files: |
            reports/junit-test-results.xml

      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@51cc3a756ddcd398d447c044c02cb6aa83fdae95 # v1.3.0
        with:
          filename: reports/coverage.xml
          badge: false
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '60 80'

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@773744901bac0e8cbb5a0dc842800d45e9b2b405 # v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md